apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dfbod80op-nodejs
  janus-idp.io/tekton: dfbod80op-nodejs
  backstage.io/kubernetes-id: dfbod80op-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dfbod80op-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
